workflows:
  android-build:
    name: Build Android APK
    instance_type: mac_mini_m2
    max_build_duration: 60
    
    scripts:
      - name: Install Gradle
        script: |
          brew install gradle
          gradle wrapper --gradle-version 8.2
          chmod +x gradlew
      
      - name: Build Debug APK
        script: |
          ./gradlew assembleDebug --stacktrace
    
    artifacts:
      - app/build/outputs/apk/debug/*.apk
    
    publishing:
      email:
        recipients:
          - your-email@example.com
        notify:
          success: true
        failure: true
